//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using LitJson;
using UnityEngine;
using UnityEngine.UI;

namespace GraduationProject
{
	public class AnimationButton : AnimationLabel
	{
		public int id {get; private set;}
		public int order {get; set;}

		public AnimationButton ()
		{
		}

		public override void CreateMenuItem (Canvas canvas, ButtonsInfo info)
		{
			base.CreateMenuItem (canvas, info);
			id = (int)Json["ID"];
		}

		public void SetID (int i)
		{
			id = i;
		}
	}
}

