//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using LitJson;
using UnityEngine;
using UnityEngine.UI;

namespace GraduationProject
{
	public class BaseButton : BaseLabel
	{
		private Sprite[] buttonSprites;
		private int id;

		public BaseButton ()
		{
		}

		public override void CreateMenuItem (Canvas canvas, ButtonsInfo info)
		{
			string[] filePath = JsonMapper.ToObject <string[]> (Json["filePath"].ToJson ());
			buttonSprites = new Sprite[filePath.Length];
			for (int i=0; i<filePath.Length; i++)
			{
				buttonSprites[i] = Resources.Load (defaultPath+filePath[i], typeof(Sprite)) as Sprite;
			}
			buttonImage = new Image[1];
			
			information = info;
			
			for (int i=0; i<buttonImage.Length; i++)
			{
				GameObject buttonObject = new GameObject ();
				buttonObject.name = filePath[i];
				buttonObject.transform.parent = canvas.transform;
				
				buttonImage[i] = buttonObject.AddComponent <Image> ();
				buttonImage[i].sprite = buttonSprites[0];
				buttonImage[i].rectTransform.anchorMax = Vector2.zero;
				buttonImage[i].rectTransform.anchorMin = Vector2.zero;
				buttonImage[i].rectTransform.pivot = new Vector2 (information.pivot[0]/2f, information.pivot[1]/2f);
				
				buttonImage[i].rectTransform.position = new Vector3 (information.position.x*ratio_width, information.position.y*ratio_height, 0f);
				buttonImage[i].rectTransform.sizeDelta = new Vector2 (information.size.x*ratio_width, information.size.y*ratio_height);
			}

			id = (int)Json["ID"];
		}

		public override void ButtonAnimation ()
		{
			
		}

		public void ButtonEvent (int nowSelect)
		{
			buttonImage[0].sprite = buttonSprites[nowSelect == id ? 0 : 1];
		}
	}
}

