//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace GraduationProject
{
	public class BaseMenu
	{
		protected DataManager dataManager;
		protected SoundManager soundManager;
		protected Cursor cursor;
		protected ChangeLabel explanatoryText;
		protected Canvas canvas;
		protected List<AnimationLabel> labelList;
		protected List<AnimationButton> buttonList;
		public int counter {get; protected set;}
		protected float time;
		public BaseMenu nextMenu {get; protected set;}
		protected ButtonsInfo[] buttonsInfo;   
		protected string productionFile;
		protected bool isDelete = false;

		public BaseMenu (Canvas canv, SoundManager soundMan)
		{
			canvas = canv;
			labelList = new List<AnimationLabel> ();
			buttonList = new List<AnimationButton> ();
			counter = 0;
			nextMenu = this;
			dataManager = DataManager.GetInstance ();
			soundManager = soundMan;
		}

		public virtual void CreateBackGround ()
		{
		}

		public virtual void Execute (InputManager inputManager, IProductionObserver observer)
		{

		}

		public virtual void ChangeEvent (int var)
		{

		}

		public virtual void ButtonEvent ()
		{

		}

		public virtual void CancelEvent ()
		{

		}

		public virtual List<BaseProduction> GetProductionList ()
		{
			return new List<BaseProduction> ();
		}

		protected virtual void Delete ()
		{
			foreach (AnimationButton button in buttonList)
				button.Destory ();
			foreach (AnimationLabel label in labelList)
				label.Destory ();
			
			buttonList.Clear ();
			labelList.Clear ();
		}
	}
}

