//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using LitJson;
using UnityEngine;
using UnityEngine.UI;

namespace GraduationProject
{
	public class Cursor : AnimationLabel
	{
		public int select {get; set;} 
		public int max_number {get; set;}

		public Cursor ()
		{
			select = 0;
		}

		public void ChangeSelect (int var)
		{
			select += var;
			if (select < 0) select = max_number-1;
			if (select >= max_number) select = 0;
		}
	}
}

