//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using LitJson;
using UnityEngine;
using UnityEngine.UI;

namespace GraduationProject
{
	public class FilldCursor : AnimationCursor
	{
		private float speed = 0.05f;
		public FilldCursor () : base ()
		{
		}

		public override void CreateMenuItem (Canvas canvas)
		{
			string[] filePath = JsonMapper.ToObject <string[]> (Json["filePath"].ToJson ());
			buttonImage = new Image[filePath.Length];
			
			information = new ButtonsInfo ();
			information.position = new Vector2 ((float)((int)Json["position_x"]), (float)((int)Json["position_y"]));
			information.size = new Vector2 ((float)((int)Json["width"]), (float)((int)Json["height"]));
			information.pivot = JsonMapper.ToObject <float[]> (Json["pivot"].ToJson ());
			
			for (int i=0; i<buttonImage.Length; i++)
			{
				GameObject buttonObject = new GameObject ();
				buttonObject.name = filePath[i];
				buttonObject.transform.parent = canvas.transform;
				
				buttonImage[i] = buttonObject.AddComponent <Image> ();
				buttonImage[i].sprite = Resources.Load (defaultPath+filePath[i], typeof(Sprite)) as Sprite;
				buttonImage[i].rectTransform.anchorMax = Vector2.zero;
				buttonImage[i].rectTransform.anchorMin = Vector2.zero;
				buttonImage[i].rectTransform.pivot = new Vector2 (information.pivot[0]/2f, information.pivot[1]/2f);
				
				buttonImage[i].rectTransform.position = new Vector3 (information.position.x*ratio_width, information.position.y*ratio_height, 0f);
				buttonImage[i].rectTransform.sizeDelta = new Vector2 (information.size.x*ratio_width, information.size.y*ratio_height);

				buttonImage[i].type = Image.Type.Filled;
				string method = (string)Json["fillMethod"];
				
				switch (method)
				{
				case	"Horizontal":
					buttonImage[i].fillMethod = Image.FillMethod.Horizontal;
					break;
				case	"Vertical":
					buttonImage[i].fillMethod = Image.FillMethod.Vertical;
					break;
				case	"Radial360":
					buttonImage[i].fillMethod = Image.FillMethod.Radial360;
					break;
				case	"Radial180":
					buttonImage[i].fillMethod = Image.FillMethod.Radial180;
					break;
				case	"Radial90":
					buttonImage[i].fillMethod = Image.FillMethod.Radial90;
					break;
				}
				
				buttonImage[i].fillOrigin = (int)Json["fillOrigin"];
				buttonImage[i].fillAmount = 0;
			}
		}

		public override void StartAnimation (float targetSize, float time)
		{
			for (int i=0; i<buttonImage.Length; i++)
			{
				buttonImage[i].fillAmount = 0;
			}
		}

		public override void CursorAnimation ()
		{
			for (int i=0; i<buttonImage.Length; i++)
			{
				if (buttonImage[i].fillAmount < 1)
				{
					buttonImage[i].fillAmount += speed;
				}
			}
		}
	}
}

