//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;

namespace GraduationProject
{
	public class BlinkImage : BaseProduction
	{
		private Image blinkImage;

		public BlinkImage () : base ()
		{
		}

		public override void Execute (ProductionInfo information, IProductionObserver observer)
		{
			float alpha = Mathf.PingPong (Time.time, target)/ target;
			
			blinkImage.color = new Color (0.5f, 0.5f, 0.5f, alpha);

			if (information.inputManager.StartButton == 1)
			{
				information.soundManager.PlaySE (0);
				observer.NextCommand ();
			}

		}

		public override void CreateProduction (Canvas canvas)
		{
			skip = false;

			GameObject imageObject = new GameObject ();
			imageObject.name = "Image";
			imageObject.transform.parent = canvas.transform;
			
			blinkImage = imageObject.AddComponent<Image> ();
			blinkImage.sprite = Resources.Load ((string)Json["filePath"], typeof(Sprite)) as Sprite;

			blinkImage.rectTransform.anchorMax = Vector2.zero;
			blinkImage.rectTransform.anchorMin = Vector2.zero;
			blinkImage.rectTransform.pivot = Vector2.zero;
			blinkImage.rectTransform.position = new Vector3 ((float)((int)Json["x"])*ratio_width, (float)((int)Json["y"])*ratio_height, 0f);
			blinkImage.rectTransform.sizeDelta = new Vector2 ((float)((int)Json["width"])*ratio_width, (float)((int)Json["height"])*ratio_height);

			target = (float) ((int)Json["target"]);
			blinkImage.color = new Color (1f, 1f, 1f, 0f);
		}
	}
}

