//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace GraduationProject
{
	public class CameraWork : BaseProduction
	{
		private float euler_x = 0f;
		private float euler_y = 0f;
		private float euler_z = 0f;

		public CameraWork ()
		{

		}

		public override void Execute (ProductionInfo information, IProductionObserver observer)
		{
			base.Execute (information, observer);

			if (skip)
			{
				float target_x = information.camera.transform.eulerAngles.x + euler_x*counter;
				float target_y = information.camera.transform.eulerAngles.y + euler_y*counter;
				float target_z = information.camera.transform.eulerAngles.z + euler_z*counter;

				information.camera.transform.eulerAngles = new Vector3 (target_x, target_y, target_z);
				observer.NextCommand ();
			}
			else
			{
				float target_x = information.camera.transform.eulerAngles.x + euler_x;
				float target_y = information.camera.transform.eulerAngles.y + euler_y;
				float target_z = information.camera.transform.eulerAngles.z + euler_z;

				counter --;
				information.camera.transform.eulerAngles = new Vector3 (target_x, target_y, target_z);
				
				if (counter <= 0)
				{
					observer.NextCommand ();
				}
			}
		}
		
		public override void CreateProduction (Canvas canvas)
		{
			time = (int)Json["time"];
			counter = time;

			euler_x = (float)((int)Json ["x"])/(float)time;
			euler_y = (float)((int)Json ["y"])/(float)time;
			euler_z = (float)((int)Json ["z"])/(float)time;


		}
	}
}

