//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine.UI;
using UnityEngine;

namespace GraduationProject
{
	//演出フェードアウトクラス
	public class FadeProduction : BaseProduction
	{
		private Image fadeImage;

		public FadeProduction () : base ()
		{
			time = 60;
			counter = time;
		}
			
		public override void Execute (ProductionInfo information, IProductionObserver observer)
		{
			float alpha = Mathf.Lerp (current, target, 1f - ((float)counter / (float)time));

			information.fadeBackGroung.color = new Color (1f, 1f, 1f, alpha);
			counter --;

			if (counter <= 0)
			{
				observer.NextCommand ();
			}
		}

		public override void CreateProduction (Canvas canvas)
		{
			current = (float)((int)Json["current"]);
			target = (float)((int)Json["target"]);
			skip = false;
		}
	}
}

