//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEngine.UI;

namespace GraduationProject
{
	public class FilldImage : BaseProduction
	{
		private Image image;

		public FilldImage () : base ()
		{

		}

		public override void Execute (ProductionInfo information, IProductionObserver observer)
		{
			float amount = Mathf.Lerp (0f, 1f, 1f-((float)counter / (float)time));
			
			image.fillAmount = amount;
			counter --;
			
			if (counter <= 0)
			{
				observer.NextCommand ();
			}
		}
		
		public override void CreateProduction (Canvas canvas)
		{
			GameObject imageObject = new GameObject ();
			imageObject.name = "Image";
			imageObject.transform.parent = canvas.transform;
			
			image = imageObject.AddComponent<Image> ();
			image.sprite = Resources.Load ((string)Json["filePath"], typeof(Sprite)) as Sprite;
			image.type = Image.Type.Filled;
		
			image.rectTransform.anchorMax = Vector2.zero;
			image.rectTransform.anchorMin = Vector2.zero;
			image.rectTransform.pivot = Vector2.zero;
			image.rectTransform.position = new Vector3 ((float)((int)Json["x"])*ratio_width, (float)((int)Json["y"])*ratio_height, (float)((int)Json["z"]));
			image.rectTransform.sizeDelta = new Vector2 ((float)((int)Json["width"])*ratio_width, (float)((int)Json["height"])*ratio_height);

			string method = (string)Json["fillMethod"];

			switch (method)
			{
			case	"Horizontal":
				image.fillMethod = Image.FillMethod.Horizontal;
				break;
			case	"Vertical":
				image.fillMethod = Image.FillMethod.Vertical;
				break;
			case	"Radial360":
				image.fillMethod = Image.FillMethod.Radial360;
				break;
			case	"Radial180":
				image.fillMethod = Image.FillMethod.Radial180;
				break;
			case	"Radial90":
				image.fillMethod = Image.FillMethod.Radial90;
				break;
			}

			image.fillOrigin = 135;
		
			time = (int)Json["time"];
			counter = time;
		}
	}
}

