//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace GraduationProject
{
	public class MenuProduction : BaseProduction
	{
		public MenuProduction ()
		{
		}

		public override void Execute (ProductionInfo information, IProductionObserver observer)
		{
			observer.CreateMenu ();
			observer.NextCommand ();
		}
		
		public override void CreateProduction (Canvas canvas)
		{
		}
	}
}

