//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using LitJson;

namespace GraduationProject
{
	public class SoundProduction : BaseProduction
	{
		private int bgmNumber;

		public SoundProduction ()
		{
		}

		public override void Execute (ProductionInfo information, IProductionObserver observer)
		{
			information.soundManager.PlayBGM (bgmNumber);
			observer.NextCommand ();
		}
		
		public override void CreateProduction (Canvas canvas)
		{
			bgmNumber = (int)Json["number"];
		}
	}
}

